exxonmobil/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^upload/',include('upload.urls')),    
    # url(r'^dropbox$', include(django_dropbox_upload_handler_urls)),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.conf.urls import url



from .import views 

app_name='upload'

urlpatterns = [

    url(r'^$', views.login,name='login'),
	url(r'^filled$', views.filled,name='filled'),
	
	# url(r'^uploaded$', views.uploaded,name='uploaded'),
	# url(r'^done$', views.done,name='done'),
    ]

upload/models.py
from __future__ import unicode_literals

from django.db import models

def user_directory_path(instance, filename):
	return 'Client/'+ instance.name+'.jpg'

class Person(models.Model):
	name=models.CharField(max_length=100)
	email=models.EmailField(max_length=100)
	phone=models.CharField(max_length=100)
	file=models.FileField(max_length=100,upload_to=user_directory_path)
	ip_addr = models.CharField(max_length=20, default='')
	country=models.CharField(max_length=100, default='')
	country_code=models.CharField(max_length=100, default='')
	city=models.CharField(max_length=100, default='')
	city_postal_code=models.CharField(max_length=100, default='')
	latitude=models.CharField(max_length=100, default='')
	longitude=models.CharField(max_length=100, default='')
	dma_code=models.CharField(max_length=100, default='')
	def __str__(self):
		return self.name

upload/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from .models import Person
# from django.contrib.gis import geoip2
# from django.contrib.gis.geoip2 import GeoIP2
# Create your views here.

def login(request):
	# return HttpResponse('sff')
	return render(request,'upload/upload_form.html')


def filled(request):
# 	if request.method == "POST":
# 		name = request.POST['name']
# 		email = request.POST['e-mail']
# 		phone = request.POST['phone']
# 		client_ip = request.META['REMOTE_ADDR']
# 		print client_ip
# 		g=GeoIP2()
# 		city=g.city(client_ip)


# 		if 'file' in request.FILES:
# 			myfile=request.FILES['file']
# 		else:
# 			myfile = None
# 		x=Person(name=name,email=email,phone=phone,file=myfile,ip_addr=client_ip,country=city['country_name'],
# 			country_code=city['country_code'],
# 			city=city['city'],
# 			city_postal_code=city['postal_code'],
# 			latitude=city['latitude'],
# 			longitude=city['longitude'],
# 			dma_code=city['dma_code'],)
# 		x.save()

# 		return render(request,'upload/success.html',{'country':city['country_name'],
# 			'country_code':city['country_code'],
# 			'city':city['city'],
# 			'city_postal_code':city['postal_code'],
# 			'latitude':city['latitude'],
# 			'longitude':city['longitude'],
# 			'dma_code':city['dma_code'],

# 			})

upload/templates/upload/success.html
Details of your file upload location: </br> </br>

Country  Name :{{country}} </br>
Country Code :{{country_code}}</br>
City Name : {{city}}</br>
City Postal Code : {{city_postal_code}}</br>
Latitude:{{latitude}}</br>
Longitude:{{longitude}}</br>
Dma :{{dma_code}}</br>

upload/templates/upload/upload_form.html
<div class ="container-fluid">

	<div class="row">
		{% load static %}
		<body background="https://static.pexels.com/photos/36764/marguerite-daisy-beautiful-beauty.jpg">
			<link rel="stylesheet" href="{% static 'upload/css/style.css' %}">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class ="panel-body">
				<h1><font color="white">WELCOME TO Exxon_Mobilr</font></h1>
					{% if error_message %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}		
					<form action="{% url 'upload:filled' %}" id="msform"  enctype="multipart/form-data"  name="form_details" method="POST" >
						{% csrf_token %}
						<form>
							<label for="1" font-color="#fff">Name:</label><br>
							<input id="1" type="text" name="name" required="true"><br>
							<label for="2" color="white">E-mail:</label><br>
							<input id="2" type="email" name="e-mail" required="true"><br>
							<label for="3" color="white">Phone:</label><br>
							<input id="3" type="phone" name="phone" required="true"><br>
							<br>	
							<label for="4" color="white"> Attach Image to Upload</label>					
							<input id="4" type="file" name="file" required="true"><br>
							<br>
							<button type="submit" onclick="alert('Are you sure this is the final file ?')" class="btn btn-success">Submit</button>
							</div>

						</form>